services:

  postgres:
    image: postgres:16
    container_name: barberflow-postgres
    restart: always

    environment:
      POSTGRES_USER: barberflow
      POSTGRES_PASSWORD: barberflow_password
      POSTGRES_DB: barberflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: