export const PROFESSIONAL_DEFAULT_PAGE_SIZE = 20;
export const PROFESSIONAL_MAX_PAGE_SIZE = 100;
export const PROFESSIONAL_NAME_MAX_LENGTH = 120;
export const PROFESSIONAL_BIO_MAX_LENGTH = 2000;
export const PROFESSIONAL_PHONE_MAX_LENGTH = 30;
export const PROFESSIONAL_SPECIALTY_MAX_LENGTH = 120;
export const PROFESSIONAL_AVATAR_MAX_LENGTH = 2048;
export const PROFESSIONAL_SEARCH_MAX_LENGTH = 120;
